### ISSUE TITLE
RStudio template fails to run

### ISSUE THREAD

**Issue by pitkant** [CSCfi/rstudio-openshift#11]
Fails with the following error when attempting to run the RStudio template with default settings:

**nginx-okd:**
Pulling image nginx:alpine ...
error: build error: failed to pull image: missing signature key

RStudio events:
12:48:56 PM | Normal | Deprovisioning | The instance is being deprovisioned asynchronously
-- | -- | -- | --
12:48:56 PM | Warning | Starting Instance Orphan Mitigation | The instance provision call failed with an ambiguous error; attempting to deprovision the instance in order to mitigate an orphaned resource
12:48:56 PM | Warning | Provision Call Failed | Provision call failed: readiness failed on BuildConfig openmuse/nginx-okd

**Comment by trispera** [comment]
Hello Pyry.

This error occurs because the image format (`oci`) is not supported on Rahti, only the `docker` format.

```sh
$ docker manifest inspect docker.io/nginx:alpine
"mediaType": "application/vnd.oci.image.index.v1+json",
```

There are workarounds which are explained in our documentation https://docs.csc.fi/support/faq/get-image-format/#unsupported-image-format

We'll try to find a suitable image with the correct image format, otherwise, you should upload the image to your project registry using skopeo (https://github.com/containers/skopeo). It will convert the image from `oci` to `docker`

**Comment by trispera** [comment]
PR created: https://github.com/CSCfi/rstudio-openshift/pull/12
It will be merged as soon as possible

**Comment by pitkant** [comment]
~~@trispera thank you for the prompt response. However, PR #12 does not seem to fix the problem~~

Fixed the problem when cloning this repository and running the `oc` magic words in terminal
